# Generated by Django 3.0.4 on 2020-03-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0005_auto_20200309_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
